"use strict";
(function (CREDIT) {
    CREDIT[CREDIT["CASH"] = 0] = "CASH";
    CREDIT[CREDIT["ONE_MONTH"] = 30] = "ONE_MONTH";
    CREDIT[CREDIT["TWO_MONTH"] = 60] = "TWO_MONTH";
    CREDIT[CREDIT["THREE_MONTH"] = 90] = "THREE_MONTH";
})(exports.CREDIT || (exports.CREDIT = {}));
var CREDIT = exports.CREDIT;
(function (FUTURES) {
    FUTURES[FUTURES["IMMEDIATE"] = 0] = "IMMEDIATE";
    FUTURES[FUTURES["THREE_MONTH"] = 1] = "THREE_MONTH";
    FUTURES[FUTURES["SIX_MONTH"] = 2] = "SIX_MONTH";
})(exports.FUTURES || (exports.FUTURES = {}));
var FUTURES = exports.FUTURES;
(function (DELIVERY) {
    DELIVERY[DELIVERY["IMMEDIATE"] = 0] = "IMMEDIATE";
    DELIVERY[DELIVERY["NEXT_PERIOD"] = 1] = "NEXT_PERIOD";
    DELIVERY[DELIVERY["AFTERNEXT_PERIOD"] = 2] = "AFTERNEXT_PERIOD";
})(exports.DELIVERY || (exports.DELIVERY = {}));
var DELIVERY = exports.DELIVERY;
(function (QUALITY) {
    QUALITY[QUALITY["LQ"] = 0] = "LQ";
    QUALITY[QUALITY["MQ"] = 1] = "MQ";
    QUALITY[QUALITY["HQ"] = 2] = "HQ";
})(exports.QUALITY || (exports.QUALITY = {}));
var QUALITY = exports.QUALITY;
(function (SHIFT_LEVEL) {
    SHIFT_LEVEL[SHIFT_LEVEL["SINGLE"] = 0] = "SINGLE";
    SHIFT_LEVEL[SHIFT_LEVEL["DOUBLE"] = 1] = "DOUBLE";
    SHIFT_LEVEL[SHIFT_LEVEL["TREBLE"] = 2] = "TREBLE";
})(exports.SHIFT_LEVEL || (exports.SHIFT_LEVEL = {}));
var SHIFT_LEVEL = exports.SHIFT_LEVEL;
(function (PERIODS) {
    PERIODS[PERIODS["QUARTER"] = 3] = "QUARTER";
    PERIODS[PERIODS["HALF_YEAR"] = 6] = "HALF_YEAR";
    PERIODS[PERIODS["YEAR"] = 12] = "YEAR";
})(exports.PERIODS || (exports.PERIODS = {}));
var PERIODS = exports.PERIODS;
(function (IMPROVEMENT_TYPE) {
    IMPROVEMENT_TYPE[IMPROVEMENT_TYPE["NONE"] = 0] = "NONE";
    IMPROVEMENT_TYPE[IMPROVEMENT_TYPE["MINOR"] = 1] = "MINOR";
    IMPROVEMENT_TYPE[IMPROVEMENT_TYPE["MAJOR"] = 2] = "MAJOR";
})(exports.IMPROVEMENT_TYPE || (exports.IMPROVEMENT_TYPE = {}));
var IMPROVEMENT_TYPE = exports.IMPROVEMENT_TYPE;
(function (COM_AXES) {
    COM_AXES[COM_AXES["PRICE"] = 0] = "PRICE";
    COM_AXES[COM_AXES["CONFORT"] = 1] = "CONFORT";
    COM_AXES[COM_AXES["RESISTANCE"] = 2] = "RESISTANCE";
    COM_AXES[COM_AXES["ESTHETIC"] = 3] = "ESTHETIC";
})(exports.COM_AXES || (exports.COM_AXES = {}));
var COM_AXES = exports.COM_AXES;
(function (STAR_RATINGS) {
    STAR_RATINGS[STAR_RATINGS["ONE_STAR"] = 1] = "ONE_STAR";
    STAR_RATINGS[STAR_RATINGS["TWO_STAR"] = 2] = "TWO_STAR";
    STAR_RATINGS[STAR_RATINGS["THREE_STAR"] = 3] = "THREE_STAR";
    STAR_RATINGS[STAR_RATINGS["FOUR_STAR"] = 4] = "FOUR_STAR";
    STAR_RATINGS[STAR_RATINGS["FIVE_STAR"] = 5] = "FIVE_STAR";
})(exports.STAR_RATINGS || (exports.STAR_RATINGS = {}));
var STAR_RATINGS = exports.STAR_RATINGS;
(function (ACTIVITY) {
    ACTIVITY[ACTIVITY["OPERATING"] = 0] = "OPERATING";
    ACTIVITY[ACTIVITY["FINANCING"] = 1] = "FINANCING";
    ACTIVITY[ACTIVITY["INVESTING"] = 2] = "INVESTING";
})(exports.ACTIVITY || (exports.ACTIVITY = {}));
var ACTIVITY = exports.ACTIVITY;
;
// S&P
(function (CREDIT_SHORTTERM_RATING) {
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["A1_PLUS"] = 9986] = "A1_PLUS";
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["A1"] = 9773] = "A1";
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["A2"] = 9332] = "A2";
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["A3"] = 8413] = "A3";
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["B"] = 6915] = "B";
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["C"] = 5000] = "C";
    CREDIT_SHORTTERM_RATING[CREDIT_SHORTTERM_RATING["D"] = 2776] = "D";
})(exports.CREDIT_SHORTTERM_RATING || (exports.CREDIT_SHORTTERM_RATING = {}));
var CREDIT_SHORTTERM_RATING = exports.CREDIT_SHORTTERM_RATING;
(function (CREDIT_LONGTERM_RATING) {
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["AAA"] = 9990] = "AAA";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["AA_PLUS"] = 9988] = "AA_PLUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["AA"] = 9986] = "AA";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["AA_MINUS"] = 9938] = "AA_MINUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["A_PLUS"] = 9773] = "A_PLUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["A"] = 9599] = "A";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["A_MINUS"] = 9332] = "A_MINUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["BBB_PLUS"] = 8944] = "BBB_PLUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["BBB"] = 8413] = "BBB";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["BBB_MINUS"] = 7734] = "BBB_MINUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["BB_PLUS"] = 6915] = "BB_PLUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["BB"] = 6554] = "BB";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["BB_MINUS"] = 6179] = "BB_MINUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["B_PLUS"] = 5987] = "B_PLUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["B"] = 5793] = "B";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["B_MINUS"] = 5398] = "B_MINUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["CCC_PLUS"] = 5000] = "CCC_PLUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["CCC"] = 4364] = "CCC";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["CCC_MINUS"] = 4052] = "CCC_MINUS";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["CC"] = 2776] = "CC";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["C"] = 2297] = "C";
    CREDIT_LONGTERM_RATING[CREDIT_LONGTERM_RATING["D"] = 1379] = "D";
})(exports.CREDIT_LONGTERM_RATING || (exports.CREDIT_LONGTERM_RATING = {}));
var CREDIT_LONGTERM_RATING = exports.CREDIT_LONGTERM_RATING;
(function (SPACE_USAGES) {
    SPACE_USAGES[SPACE_USAGES["MACHINES"] = 0] = "MACHINES";
    SPACE_USAGES[SPACE_USAGES["WORKERS"] = 1] = "WORKERS";
    SPACE_USAGES[SPACE_USAGES["STOCKS"] = 2] = "STOCKS";
})(exports.SPACE_USAGES || (exports.SPACE_USAGES = {}));
var SPACE_USAGES = exports.SPACE_USAGES;
(function (PLC_STAGE) {
    PLC_STAGE[PLC_STAGE["INTRODUCTION"] = 0] = "INTRODUCTION";
    PLC_STAGE[PLC_STAGE["GROWTH"] = 1] = "GROWTH";
    PLC_STAGE[PLC_STAGE["MATURITY_BEGIN"] = 2] = "MATURITY_BEGIN";
    PLC_STAGE[PLC_STAGE["MATURITY_END"] = 3] = "MATURITY_END";
    PLC_STAGE[PLC_STAGE["DECLINE"] = 4] = "DECLINE";
})(exports.PLC_STAGE || (exports.PLC_STAGE = {}));
var PLC_STAGE = exports.PLC_STAGE;
// http://www.learnmarketing.net/Types%20of%20%20product%20life%20cycles.htm
(function (PLC_TYPE) {
    PLC_TYPE[PLC_TYPE["CLASSICAL"] = 0] = "CLASSICAL";
    PLC_TYPE[PLC_TYPE["RAPID_PENETRATION"] = 1] = "RAPID_PENETRATION";
    PLC_TYPE[PLC_TYPE["GROWTH_MATURITY"] = 2] = "GROWTH_MATURITY";
    PLC_TYPE[PLC_TYPE["STABLE_MATURITY"] = 3] = "STABLE_MATURITY";
    PLC_TYPE[PLC_TYPE["GROWTH_DECLINE_PLATEAU"] = 4] = "GROWTH_DECLINE_PLATEAU";
})(exports.PLC_TYPE || (exports.PLC_TYPE = {}));
var PLC_TYPE = exports.PLC_TYPE;
//# sourceMappingURL=ENUMS.js.map